name: vucutkitleindexhesaplama
description: Vücut kitle endeks hesaplama uygulamasıdır.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.5.5+1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

flutter_icons:
  image_path: "images/user.png" 
  android: true
  ios: true


  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: fonts/SF-Pro-Display-Black.otf
          weight: 900
